version: "3.8"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  eureka-server:
    build: ./eureka-server
    image: dayvsonsales/eureka-server
    ports:
      - "8761:8761"
  zuul-server:
    depends_on:
      - eureka-server
    build: ./zuul-server
    image: dayvsonsales/zuul-server
    ports:
      - "8762:8762"
  playlists-suggestion:
    depends_on:
      - redis
      - eureka-server
      - zuul-server
    restart: always
    build: ./playlists-suggestion
    image: dayvsonsales/playlists-suggestion
    ports:
      - "3333:3333"
